version: '3.3'

services:
  app:
    image: 'test:latest'
    build:
      context: .
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=Sergtsop123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8095:8095"


  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Sergtsop123
    ports:
      - "5432:5432"
